nodeLinker: node-modules
enableInlineHunks: true
supportedArchitectures:
  # wasm32 is needed by @node-rs/xxhash-wasm32-wasi otherwise it is not installed
  os:
    - current
  cpu:
    - current
    - wasm32
  libc:
    - current